# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microplate < Formula
  desc "CLI that allows to update boilerplates with ease"
  homepage "https://github.com/mprostakk/microplate"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mprostakk/microplate/releases/download/0.0.1/microplate_Darwin_x86_64.tar.gz"
      sha256 "f20db2faa6ddbb0de484fe08bd35ff538fd48be4161258ab0f98782a4464c4bf"

      def install
        bin.install "microplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mprostakk/microplate/releases/download/0.0.1/microplate_Darwin_arm64.tar.gz"
      sha256 "1a65fd28870b354036b472bcccc9498b54f98120882c71e634535bad7d9f3ef9"

      def install
        bin.install "microplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mprostakk/microplate/releases/download/0.0.1/microplate_Linux_x86_64.tar.gz"
      sha256 "64b3ff35904edb8ada1cae6615e412e24dd8ced6452bca6b54a6b09d8aab215e"

      def install
        bin.install "microplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mprostakk/microplate/releases/download/0.0.1/microplate_Linux_arm64.tar.gz"
      sha256 "2959543f5d32c7467a9133e5babd5b998ce43f5e523f2d2ef2f7e7a18d8aea37"

      def install
        bin.install "microplate"
      end
    end
  end
end
